---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-benchmark-vankichi-github-io-v1-benchmarkoperator
  failurePolicy: Fail
  name: mbenchmarkoperator.kb.io
  rules:
  - apiGroups:
    - benchmark.vankichi.github.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - benchmarkoperators
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-benchmark-vankichi-github-io-v1-benchmarkoperator
  failurePolicy: Fail
  name: vbenchmarkoperator.kb.io
  rules:
  - apiGroups:
    - benchmark.vankichi.github.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - benchmarkoperators
  sideEffects: None
