# permissions for end users to view benchmarkoperators.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: benchmarkoperator-viewer-role
rules:
- apiGroups:
  - benchmark.vankichi.github.io
  resources:
  - benchmarkoperators
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - benchmark.vankichi.github.io
  resources:
  - benchmarkoperators/status
  verbs:
  - get
