---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - benchmark.vankichi.github.io
  resources:
  - valdbenchmarkoperators
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - benchmark.vankichi.github.io
  resources:
  - valdbenchmarkoperators/finalizers
  verbs:
  - update
- apiGroups:
  - benchmark.vankichi.github.io
  resources:
  - valdbenchmarkoperators/status
  verbs:
  - get
  - patch
  - update
