apiVersion: benchmark.vankichi.github.io/v1
kind: BenchmarkOperator
metadata:
  name: benchmarkoperator-sample
spec:
  # TODO(user): Add fields here
  target:
    host: "localhost"
    port: 8080
  dataset:
    group: "test"
    indexes: 1000
    name: "fashion-mnist"
    range:
      start: 0
      end: 1000
