apiVersion: benchmark.vankichi.github.io/v1
kind: BenchmarkOperator
metadata:
  name: sample
spec:
  # TODO(user): Add fields here
  target:
    host: "localhost"
    port: 8080
  dataset:
    group: "test"
    indexes: 1000
    name: "fashion-mnist"
    range:
      start: 0
      end: 1000
  jobs:
    - replica: 1
      num: 10
      min_num: 10
      iter: 1000
      job_type: "search"
      dimension: 784
      timeout: "10s"
      target:
        host: "localhost"
        port: 8080
      dataset:
        group: "test"
        indexes: 1000
        name: "fashion-mnist"
        range:
          start: 0
          end: 1000
